"""Add AnalysisResults table

Revision ID: 44521cc24807
Revises: c5c1ce350045
Create Date: 2025-01-10 14:56:42.605713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44521cc24807'
down_revision = 'c5c1ce350045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('classification', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['processed_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_results')
    # ### end Alembic commands ###
