"""Update Patient Model 5

Revision ID: 495e2a1a076a
Revises: caaf9f3a10c6
Create Date: 2024-12-17 23:14:53.896550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495e2a1a076a'
down_revision = 'caaf9f3a10c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('group', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('raw_eeg_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('processed_eeg_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('model_result', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=1),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'users', ['doctor_id'], ['id'])
        batch_op.drop_column('age')
        batch_op.drop_column('name')
        batch_op.drop_column('diagnosis')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnosis', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('gender',
               existing_type=sa.String(length=1),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('doctor_id')
        batch_op.drop_column('model_result')
        batch_op.drop_column('processed_eeg_file')
        batch_op.drop_column('raw_eeg_file')
        batch_op.drop_column('notes')
        batch_op.drop_column('group')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
